version: '3.7'

services:
   gentoo_packer:
      image: ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION}
      build: 
         context: ./packer
      entrypoint: "bash -c"
      command: "'while sleep 3600; do :; done'"
      stdin_open: true
      tty: true
      privileged: true
      volumes:
         - "./packer/assets:/packer/"
      network_mode: "host"
      #ports:
      #    - "5959:5959"
      #    - "2222:2229"
      #    - "8888:10082"

