version: '3.7'

services:
   gentoo_packer:
      image: ${REGISTRY_URL}/${IMAGE_NAME}:${VERSION}
      privileged: true
      volumes:
         - "./image/assets:/packer"
         - "./image/cache:/packer-cache"
      network_mode: "host"
      environment:
         - SOURCE_NAME=qemu.gentoo
         - SSH_LIVE_USERNAME=root
         - SSH_LIVE_PASSWORD=toortrort@orto0rTempPASSWORD
         - ANSIBLE_EXTRA_VARS=generated_user=antoine generated_group=users gentoo_version=20201111T214503Z
         - ANSIBLE_PLAYBOOK=/packer/ansible/playbook-gentoo.yml
         - ISO_CHECKSUM=file:http://distfiles.gentoo.org/releases/amd64/autobuilds/current-install-amd64-minimal/install-amd64-minimal-20201111T214503Z.iso.DIGESTS
         - ISO_URL=http://distfiles.gentoo.org/releases/amd64/autobuilds/current-install-amd64-minimal/install-amd64-minimal-20201111T214503Z.iso
      #ports:
      #    - "5900:5900/udp"
      #    - "2222:2229"
      #    - "10082:10082"

