---
# file: playbook-gentoo.yml

- hosts: default
  become: true
  pre_tasks:
    - name: "check ansible required param"
      assert:
        that:
          - ssh_pub is defined
          - generated_user is defined 
          - generated_group is defined 
        fail_msg: "Pass param ssh_pub, generated_user and generated_group to launch this playbook"
  roles:
     - prepare
     - setup

