---
# setup gentoo

- name: "Ensure group {{ generated_group }} exists"
  group:
    name: "{{ generated_group }}"

- name: "create {{ generated_user }} user and {{ generated_group }} group"
  user:
    name: "{{ generated_user }}"
    comment: "Login user generate by ansible"
    group: "{{ generated_group }}"

- name: "copy ssh key to {{ user_home }}/.ssh/authorized_keys"
  lineinfile:
    path: "{{ user_home }}/.ssh/authorized_keys"
    line: "{{ ssh_pub }}"
    create: yes
    owner: "{{ generated_user }}"
    group: "{{ generated_user }}"
    mode: '0600'

- name: Ensure SELinux is set to permissive mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive


