---
# partition disk to install gentoo

- name: "Create a new primary partition for LVM"
  parted:
    device: /dev/sda
    name: "root"
    label: gpt
    number: 1
    flags: [ lvm ]
    state: present

