---
# partition disk to install gentoo

- name: "Create a new primary partition with a size of 1GiB"
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_end: 1GiB

- name: "Create a new primary partition for LVM"
  parted:
    device: /dev/sdb
    number: 2
    flags: [ lvm ]
    state: present
    part_start: 1GiB


