---
# setup gentoo

- name: "copy ssh key to {{ user_home }}/.ssh/authorized_keys"
  lineinfile:
    path: "{{ user_home }}/.ssh/authorized_keys"
    line: "{{ ssh_pub }}"
    create: yes
    owner: "{{ generated_user }}"
    group: "{{ generated_user }}"
    mode: '0600'

- name: Ensure SELinux is set to permissive mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=permissive

